### ISSUE TITLE
feature request

### ISSUE THREAD

**Issue by Sativarg** [Yacoby/es-search#17]
I think it would be great if when I put a word in the text box 
`<div id="indexSearch"><div id="activeForm" name="Simple">`
and then click on the button
`<input name="act" id="act" value="Search" type="submit">`

some thing other than "No results found!"  would happen.

I was looking forward to being able to locate long lost info. This must have worked once but I searched the word Qarl and got  "No results found!"... that pretty much proves to me that this resource is not working for me. It probably is not related to my setup because I tried the page in safe-mode with Firefox. In safe-mode I am not blocking any thing and all scripts should run.

The page I was trying:TES Search - http://www.tessearch.com/
Maybe that is not the correct page?

**Comment by Yacoby** [comment]
Ah, sorry about that. Something wasn't running that should have been. Should be fixed now

**Comment by Sativarg** [comment]
OH  OK thanks
Here you may like this
Spoilers though kinda
'Doctor Who' stars: 'There were tears after final scenes together' - Doctor Who News - Cult - Digital Spy - http://www.digitalspy.co.uk/tv/s7/doctor-who/news/a394075/doctor-who-stars-there-were-tears-after-final-scenes-together.html
